[package]
name = "website"
version = "0.1.0"
edition = "2024"

[dependencies]
maud = "0.27.0"
strum = { version = "0.27", features = ["derive"] }
# pollster = "0.4.0"
clap = { version = "4.5", features = ["derive"] }
Props = { path = "Props" }
image = "0.25.6"
i18n-embed = { version = "0.16", features = ["fluent-system", "desktop-requester"]}
rust-embed = "8"
unic-langid = { version ="0.9", features = ["macros"]}
thiserror = "2.0.17"
