use crate::{Link, link_logo};
use strum::Display;

#[allow(unused)]
#[derive(Debug, Display, Clone, Copy, PartialEq, PartialOrd, Eq, Ord)]
pub enum Icon {
    // 🎨 Design & KreativSoftware
    AfterEffects,
    Audacity,
    Blender,
    CreativeCloud,
    Figma,
    Houdini,
    Illustrator,
    Penpot,
    Photoshop,
    Premiere,
    XD,

    // 💻 Allgemeine EDV & Tools
    Apple,
    Excel,
    MacOS,
    Fedora,
    Fritzing,
    Git,
    GitHub,
    Linux,
    Microsoft,
    NeoVim,
    Office,
    PowerPoint,
    VSCode,
    Windows,
    Word,

    // 🔧 Programmiersprachen
    Arduino,
    Bash,
    Bootstrap,
    C,
    Cpp,
    CSharp,
    CSS,
    Docker,
    Dribbble,
    HTML,
    Java,
    JavaScript,
    Jupyter,
    Lua,
    Python,
    Rust,
    TypeScript,
    WebAssembly,
}

impl Icon {
    pub const fn name(self) -> &'static str {
        match self {
            Icon::AfterEffects => "Adobe After Effects",
            Icon::Audacity => "Audacity",
            Icon::Blender => "Blender",
            Icon::CreativeCloud => "Adobe Creative Cloud",
            Icon::Figma => "Figma",
            Icon::Illustrator => "Adobe Illustrator",
            Icon::Penpot => "Penpot",
            Icon::Photoshop => "Adobe Photoshop",
            Icon::Premiere => "Adobe Premiere Pro",
            Icon::XD => "Adobe XD",
            Icon::Houdini => "Houdini",
            Icon::Apple => "Apple",
            Icon::Excel => "Microsoft Excel",
            Icon::MacOS => "macOS",
            Icon::Microsoft => "Microsoft",
            Icon::Office => "Microsoft Office",
            Icon::PowerPoint => "Microsoft PowerPoint",
            Icon::Windows => "Windows",
            Icon::Word => "Microsoft Word",
            Icon::Arduino => "Arduino",
            Icon::Bash => "Bash",
            Icon::Bootstrap => "Bootstrap",
            Icon::C => "C",
            Icon::Cpp => "C++",
            Icon::CSharp => "C#",
            Icon::CSS => "CSS",
            Icon::Docker => "Docker",
            Icon::Dribbble => "Dribbble",
            Icon::Fedora => "Fedora",
            Icon::Fritzing => "Fritzing",
            Icon::Git => "Git",
            Icon::GitHub => "GitHub",
            Icon::HTML => "HTML",
            Icon::Java => "Java",
            Icon::JavaScript => "JavaScript",
            Icon::Jupyter => "Jupyter",
            Icon::Linux => "Linux",
            Icon::Lua => "Lua",
            Icon::NeoVim => "NeoVim",
            Icon::Python => "Python",
            Icon::Rust => "Rust",
            Icon::TypeScript => "TypeScript",
            Icon::VSCode => "VS Code",
            Icon::WebAssembly => "WebAssembly",
        }
    }
    pub const fn img_link(self) -> Link {
        match self {
            Icon::AfterEffects => link_logo!("adobe-after-effects-svgrepo-com.svg"),
            Icon::Audacity => link_logo!("Audacity_Logo.svg"),
            Icon::Blender => link_logo!("blender-svgrepo-com.svg"),
            Icon::CreativeCloud => link_logo!("adobe-creative-cloud-svgrepo-com.svg"),
            Icon::Figma => link_logo!("figma-svgrepo-com.svg"),
            Icon::Illustrator => link_logo!("adobe-illustrator-svgrepo-com.svg"),
            Icon::Penpot => link_logo!("penpot-svgrepo-com.svg"),
            Icon::Photoshop => link_logo!("adobe-photoshop-svgrepo-com.svg"),
            Icon::Premiere => link_logo!("adobe-premiere-svgrepo-com.svg"),
            Icon::XD => link_logo!("adobe-xd-svgrepo-com.svg"),
            Icon::Houdini => link_logo!("houdini_logos/houdini_badge/houdini_badge_flat.svg"),
            Icon::Apple => link_logo!("apple-svgrepo-com.svg"),
            Icon::Excel => link_logo!("ms-excel-svgrepo-com.svg"),
            Icon::MacOS => link_logo!("macos-svgrepo-com.svg"),
            Icon::Microsoft => link_logo!("microsoft-svgrepo-com.svg"),
            Icon::Office => link_logo!("office-1-logo-svgrepo-com.svg"),
            Icon::PowerPoint => link_logo!("ms-powerpoint-svgrepo-com.svg"),
            Icon::Windows => link_logo!("microsoft-windows-svgrepo-com.svg"),
            Icon::Word => link_logo!("ms-word-svgrepo-com.svg"),
            Icon::Arduino => link_logo!("arduino-svgrepo-com.svg"),
            Icon::Bash => link_logo!("bash-icon-svgrepo-com.svg"),
            Icon::Bootstrap => link_logo!("bootstrap-svgrepo-com.svg"),
            Icon::C => link_logo!("c-svgrepo-com.svg"),
            Icon::Cpp => link_logo!("c-plusplus-svgrepo-com.svg"),
            Icon::CSharp => link_logo!("c-sharp-svgrepo-com.svg"),
            Icon::CSS => link_logo!("CSS Logo.svg"),
            Icon::Docker => link_logo!("docker-svgrepo-com.svg"),
            Icon::Dribbble => link_logo!("dribbble-icon-svgrepo-com.svg"),
            Icon::Fedora => link_logo!("fedora-svgrepo-com.svg"),
            Icon::Fritzing => link_logo!("fritzing.svg"),
            Icon::Git => link_logo!("git-icon-svgrepo-com.svg"),
            Icon::GitHub => link_logo!("github-icon-svgrepo-com.svg"),
            Icon::HTML => link_logo!("html-5-no-wordmark-svgrepo-com.svg"),
            Icon::Java => link_logo!("java-svgrepo-com.svg"),
            Icon::JavaScript => link_logo!("js-svgrepo-com.svg"),
            Icon::Jupyter => link_logo!("jupyter-svgrepo-com.svg"),
            Icon::Linux => link_logo!("linux-svgrepo-com.svg"),
            Icon::Lua => link_logo!("lua-svgrepo-com.svg"),
            Icon::NeoVim => link_logo!("neovim-mark@2x.svg"),
            Icon::Python => link_logo!("python-svgrepo-com.svg"),
            Icon::Rust => link_logo!("rust-svgrepo-com.svg"),
            Icon::TypeScript => link_logo!("typescript-icon-svgrepo-com.svg"),
            Icon::VSCode => link_logo!("vs-code-svgrepo-com.svg"),
            Icon::WebAssembly => link_logo!("webassembly-svgrepo-com.svg"),
        }
    }
    pub const fn site_link(self) -> Option<&'static str> {
        match self {
            Icon::AfterEffects => None,
            Icon::Audacity => None,
            Icon::Blender => None,
            Icon::CreativeCloud => None,
            Icon::Figma => None,
            Icon::Houdini => None,
            Icon::Illustrator => None,
            Icon::Penpot => None,
            Icon::Photoshop => None,
            Icon::Premiere => None,
            Icon::XD => None,
            Icon::Apple => None,
            Icon::Excel => None,
            Icon::MacOS => None,
            Icon::Fedora => None,
            Icon::Fritzing => None,
            Icon::Git => None,
            Icon::GitHub => None,
            Icon::Linux => None,
            Icon::Microsoft => None,
            Icon::NeoVim => None,
            Icon::Office => None,
            Icon::PowerPoint => None,
            Icon::VSCode => None,
            Icon::Windows => None,
            Icon::Word => None,
            Icon::Arduino => None,
            Icon::Bash => None,
            Icon::Bootstrap => None,
            Icon::C => None,
            Icon::Cpp => None,
            Icon::CSharp => None,
            Icon::CSS => None,
            Icon::Docker => None,
            Icon::Dribbble => None,
            Icon::HTML => None,
            Icon::Java => None,
            Icon::JavaScript => None,
            Icon::Jupyter => None,
            Icon::Lua => None,
            Icon::Python => None,
            Icon::Rust => None,
            Icon::TypeScript => None,
            Icon::WebAssembly => None,
        }
    }
}
